### ISSUE TITLE
SIGSEGV with XWayland applications

### ISSUE THREAD

**Issue by iam-afk** [artemsen/swaykbdd#10]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f14f47 in ?? () from /usr/lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7f14f47 in ?? () from /usr/lib64/libc.so.6
#1  0x0000555555555ab8 in on_focus_change (wnd_id=148, app_id=0x0,
    title=0x55555555c2d0 "rcs [~/work/rcs]") at ../swaykbdd-1.3/src/main.c:49
#2  0x00005555555564ec in sway_monitor (fn_focus=fn_focus@entry=0x555555555a50 <on_focus_change>, fn_title=fn_title@entry=0x555555555cc0 <on_title_change>,
    fn_close=fn_close@entry=0x555555555a00 <on_window_close>, fn_layout=fn_layout@entry=0x5555555559a0 <on_layout_change>) at ../swaykbdd-1.3/src/sway.c:291
#3  0x0000555555555605 in main (argc=<optimized out>, argv=<optimized out>) at ../swaykbdd-1.3/src/main.c:220
```

`app_id` can be `null` for XWayland apps (Java-based applications as an example).

**Comment by artemsen** [comment]
Fixed.
Thank you!!
